"""empty message

Revision ID: 5f127833b518
Revises: a2968d968061
Create Date: 2020-09-16 20:05:35.141030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f127833b518'
down_revision = 'a2968d968061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Artist_genre_xref', 'Genres', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'Artist_genre_xref', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'Venue_genre_xref', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'Venue_genre_xref', 'Genres', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'Venue_genre_xref', type_='foreignkey')
    op.drop_constraint(None, 'Venue_genre_xref', type_='foreignkey')
    op.drop_constraint(None, 'Artist_genre_xref', type_='foreignkey')
    op.drop_constraint(None, 'Artist_genre_xref', type_='foreignkey')
    # ### end Alembic commands ###
